language: ruby
rvm:
 - 2.3.1

sudo: required
dist: trusty
services:
  - docker

before install:

script:
 - rake

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=jamesabrown/gatekeeper
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - echo $REPO
