language: ruby
rvm:
 - 2.3.1

sudo: required
dist: trusty
services:
  - docker

before install:

script:
 - bundle exec rake test

after_success:
  - export REPO=jamesabrown/gatekeeper
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -f Dockerfile -t $REPO:$COMMIT . ;
      docker push jamesabrown/gatekeeper;
      fi
