language: ruby
rvm:
 - 2.3.1

sudo: required
dist: trusty

services:
  - docker

before_script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ] && [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then echo "latest"; elif [ "$TRAVIS_PULL_REQUEST_BRANCH" ]; then echo "$TRAVIS_PULL_REQUEST_BRANCH"; else echo "$TRAVIS_BRANCH"; fi`

script:
 - bundle exec rake test

after_success:
  - export REPO=jamesabrown/gatekeeper
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -f Dockerfile -t $REPO . ;
  - docker push jamesabrown/gatekeeper;
