---
steps:
- label: ":ruby: Unit Tests"
  timeout_in_minutes: 30
  notify:
    - github_commit_status:
        context: clean-build
  agents:
    queue: ruby-2-7-5
  command:
    - bundle install
    - bundle exec rspec

- wait

- label: ":docker: Image Build"
  timeout_in_minutes: 30
  key: build_image
  agents:
    queue: buildkit-daemonless
    buildkit: true
    daemonless: true
  commands:
  - >
    buildctl-daemonless build --output type=image,\"name=invocaops/gatekeeper:$BUILDKITE_COMMIT,invocaops/gatekeeper:\$BUILDKITE_BRANCH_DOCKER_SAFE\",push=true \
                              --progress plain \
                              --frontend dockerfile.v0 \
                              --local context=. \
                              --local dockerfile=.
...
